/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package timestablestest;

import java.awt.Color;
import java.awt.GridLayout;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.util.stream.IntStream;
import javax.swing.JLabel;
import javax.swing.Timer;

/**
 *
 * @author garysmith
 */
public class TTFrameOption extends javax.swing.JFrame {
    private Integer currentI;
    private Integer currentJ;
    private Integer ans;
    private Integer [][] answers;
    private Boolean [][] passFail;
    private Boolean [][] asked;
    private Boolean [][] answeredInTime;
    private JLabel [][] labels;
    private Double sumCounted;
    private Double percentageCounted;
    private Double percentageCorrect;
    private Timer answerTimer;
    private Integer gridSize;
    private boolean isDivideOptionEnabled;
    
    /**
     * Creates new form TTFrame
     */
    public TTFrameOption() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jProgressBar1 = new javax.swing.JProgressBar();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Times Table Test");

        jLabel2.setText("jLabel2");

        jTextField1.setText("jTextField1");

        jButton1.setText("Submit");
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });

        jButton2.setText("Start");
        jButton2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton2MouseClicked(evt);
            }
        });
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jLabel3.setText("jLabel3");

        jButton3.setText("Next Question");
        jButton3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton3MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton3))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(96, 96, 96)
                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 121, Short.MAX_VALUE)
                        .addComponent(jButton1))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(91, 91, 91)
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap(59, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton2))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(34, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton3)
                        .addGap(59, 59, 59))))
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 216, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(151, 151, 151)
                .addComponent(jProgressBar1, javax.swing.GroupLayout.PREFERRED_SIZE, 338, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 12, Short.MAX_VALUE)
                .addComponent(jProgressBar1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
        setAns();
        calculate();
        jButton1.setVisible(false);
    }//GEN-LAST:event_jButton1MouseClicked

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton2MouseClicked
        generateRandomQuestion(); 
        jButton2.setVisible(false);
        jLabel2.setVisible(true);
        jTextField1.setVisible(true);
        jLabel3.setVisible(true);
        jButton1.setVisible(true);
        answerTimer.start();
    }//GEN-LAST:event_jButton2MouseClicked

    private void jButton3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton3MouseClicked
        generateRandomQuestion();
        updateUIProgress();
        answerTimer.start();
        jButton1.setVisible(true);
    }//GEN-LAST:event_jButton3MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TTFrameOption.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TTFrameOption.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TTFrameOption.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TTFrameOption.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TTFrameOption().setVisible(true);
            }
        });
    }
public void startup(){
    gridSize = 5; //13
    sumCounted = 0.0;
    isDivideOptionEnabled = true;
    answers = new Integer[gridSize][gridSize];
    passFail = new Boolean [gridSize][gridSize];
    asked = new Boolean [gridSize][gridSize];
    labels = new JLabel [gridSize][gridSize];
    answeredInTime = new Boolean[gridSize][gridSize];
    
    for (int i=0; i<gridSize; i++){
            for (int j=0; j<gridSize; j++){
                //if (isDivideOptionEnabled){
                answers [i][j] = i * j;
                passFail [i][j] = false;
                asked [i][j] = false;
                answeredInTime[i][j] = true;
            }
        }
    createBoxes();
    //Initialise the timer - set to 8s.
    this.answerTimer = new Timer(20000,new ActionListener() {

        @Override
        public void actionPerformed(ActionEvent e) {
            answeredInTime[currentI][currentJ] = false;
            answerTimer.stop();
        }
    } );
    jLabel2.setVisible(false);
    jTextField1.setVisible(false);
    jLabel3.setVisible(false);
    jButton1.setVisible(false);
    jButton3.setVisible(false);
}

public void generateRandomQuestion(){
    int totalElement = asked.length * asked[0].length;
    String selectedIndex = "";
    int numberOfSelected = 1; //Any number < totalElements
    boolean uniqueCalcFound = false;
    outerloop:
    do{
    for (int indx=0; indx<numberOfSelected; indx++){
        if (this.sumCounted > (gridSize * gridSize - 2)){
            System.out.println("Reached second from last");
            jLabel3.setText("Test Completed, well done.");
            break outerloop;
        }
        int indexToSelect = (int)(Math.random()*totalElement);
        //generate random until its unique
        while(selectedIndex.indexOf(String.valueOf(indexToSelect))>0){
            indexToSelect = (int)(Math.random()*totalElement);
        }
        selectedIndex = selectedIndex + indexToSelect;
        int xIndex = (int)indexToSelect/asked.length;
        int yIndex = indexToSelect%asked.length;
        System.out.println(xIndex + " " + yIndex);
        if (asked[xIndex][yIndex] == false) {
                    currentI = xIndex;
                    currentJ = yIndex;
                    //**
                    if(isDivideOptionEnabled){
                        setJLabel(currentI * currentJ + " / " + xIndex);
                    }else{
                        setJLabel(xIndex + " X " + yIndex );
                    }
                    jTextField1.setText("");
                    jTextField1.setColumns(5);
                    jLabel3.setText("");
                    jButton3.setVisible(false);
                    uniqueCalcFound = true;
                    answerTimer.start();
                    break outerloop;
                }
    }
    }while (uniqueCalcFound != true ); //or unanswered > 143?
}
public void updateUIProgress(){
    calculateStatus();
    this.jProgressBar1.setStringPainted(true);
    this.jProgressBar1.setValue( (int) Math.round(this.percentageCorrect));
}

public void setIntitalTimerValue(){
    this.answerTimer.setInitialDelay(3000);
}

public void calculateStatus(){
    //Sum counted
    int sumCounted = 0;
    int sumCorrect = 0;
     for (int i=0; i<gridSize; i++){
            for (int j=0; j<gridSize; j++){
                if(asked[i][j] == true){
                    sumCounted ++;
                }
                if(passFail[i][j]==true){
                    sumCorrect ++;
                }
            }
    }
    this.sumCounted = (double) sumCounted;
    this.percentageCounted = (double) 100 * sumCounted/(asked.length * asked[0].length);
    this.percentageCorrect = (double) 100 * sumCorrect/(asked.length*asked[0].length);
}
public void calculate(){
    asked [currentI][currentJ] = true;
    
    answerTimer.stop();
    
    //System.out.println("Correct answer is: " + currentI * currentJ);
    //System.out.println("Your answer was: " + ans);
    // Add new check for division...!
    if (ans == currentI * currentJ){
        jLabel3.setText("You are correct");
        passFail [currentI][currentJ] = true;
        //System.out.println("In Time? " + answeredInTime[currentI][currentJ]);
        if(answeredInTime[currentI][currentJ] == true){
            jLabel3.setText("You are correct");
            labels[currentI][currentJ].setForeground(Color.green);
        }else{
            jLabel3.setText("You are correct, but you had to think about it!");
            labels[currentI][currentJ].setForeground(Color.orange);   
            }
    }else
    {
        jLabel3.setText("You're wrong this time");
        passFail [currentI][currentJ] = false;
        labels[currentI][currentJ].setForeground(Color.red);
    }
    jButton3.setVisible(true);
}
public void setJLabel(String s){
    this.jLabel2.setText(s);
}
public void setAns(){
    this.ans = Integer.parseInt(jTextField1.getText());
}
public void createBoxes(){
    GridLayout g = new GridLayout();
    g.setColumns(asked.length);
    g.setRows(asked[0].length);
    jPanel2.setLayout(g);

    for (int i=0; i<gridSize; i++){
            for (int j=0; j<gridSize; j++){
                labels[i][j] = new JLabel(i + "x" +j, JLabel.LEFT);
                labels[i][j].setForeground(Color.gray);
                jPanel2.add(labels[i][j]);
            }
    }    
    jPanel2.setVisible(true);
}
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JProgressBar jProgressBar1;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
}
